### ISSUE TITLE
Idea for camo unlocker

### ISSUE THREAD

**Issue by FireNinja7365** [ZoDDeL/CM-Ultimate#1]
Would it be possible to make it so when you geta normal kill the cheat table.modifies what the kill counts as so that it will add to all the camos? (Such as killing a normal bot to get demon ruby or double kill/triple kill camos)

**Comment by FireNinja7365** [comment]
Also i forgot to mention but it currently doesn't work for the burning iron camo, will this be fixed soon? (I have all the camos unlocked for every gun but 1000 headshots/weapon bashes kinda sucked to get for all of them)

**Comment by ZoDDeL** [comment]
yeah i have to grind through the basic camo first to search for an easy unlock to fade camo.
but grinding basic camo on all weapons to get to the point i could research the flames camo is a bit much.
maybe you can upload your current profile so i could use it(offline) to research the flames camo.

%USERPROFILE%\AppData\LocalLow\AlfaBravoInc
and then zip the combat master subfolder and upload it somewhere for me.

**Comment by FireNinja7365** [comment]
I don't know if it would even load my profile if i gave it to you, when i tried zipping my profile and loading it on my laptop it didn't load (even after deleting the account on the laptop) but i can try to send it to you.

**Comment by FireNinja7365** [comment]
Can you add me on discord so i can send you the files privately? My username is in my github bio
