### ISSUE TITLE
cant toggle 

### ISSUE THREAD

**Issue by xsheno** [ZoDDeL/CM-Ultimate#16]
![CXZC](https://github.com/user-attachments/assets/2fdc3da3-b0ff-492f-9fb1-37288a6e4a82)
why i cant activate any of it

**Comment by xsheno** [comment]
i tried everything nothing work

**Comment by phavok12** [comment]
There was an update

**Comment by xsheno** [comment]
> There was an update

i did last table update

**Comment by FireNinja7365** [comment]
The game updated doofus, and zoddel hasn't uploaded the fixed cheat table yet

**Comment by InternetNinjo** [comment]
Project.dll is missing, it's what causing the CT to not work

![Beydeq6UIX](https://github.com/user-attachments/assets/a7214d28-fae6-4b97-a9a3-b2241c162a22)
![8XVilhesHA](https://github.com/user-attachments/assets/344da2f1-4a10-4024-8685-742ebf955caf)

**Comment by InternetNinjo** [comment]
> > There was an update
> 
> i did last table update

not the table, the game has been updated, wait for zoddel to update

**Comment by InternetNinjo** [comment]
> > ![firefox_8SHOvduLFe](https://private-user-images.githubusercontent.com/179892182/390265257-4dc01101-aadd-48ad-9e93-3a71afff19c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2OTI2NTcsIm5iZiI6MTczMjY5MjM1NywicGF0aCI6Ii8xNzk4OTIxODIvMzkwMjY1MjU3LTRkYzAxMTAxLWFhZGQtNDhhZC05ZTkzLTNhNzFhZmZmMTljMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwNzI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWZhNWU2Y2I0ZGZiNzJlMGIzM2Q3Y2UzNGU0Y2FlYTZjOTMzMjlkMzg1N2YxNTQ5ZTJmZTEyYTdjNzJiODFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tHQLzNLcQrFjd966FLJxBxfOkdi723VXyCOw9lK_Jfw) @ZoDDeL i hope you see this in UC(someone posted about what happened)
> 
> yep i noticed this diretcly after the update launched because i directly pick the Project.dll to update the "array of byte" but the dll was missing (not really). the 2 relevent dll files just got renamed back to their original names GameAssebly.dll and UnityPlayer.dll
> 
> because they changed quite alot by dropping the tripwire and the whole beebyte and obfuscation stuff, some scripts could take a while to get fixed as its not just updating AOB's but total different opcodes i have to find.

if they really just replaced those files, why do i see size difference and Project.dll being deleted?

![ptvfWYQ0It](https://github.com/user-attachments/assets/7bda5fec-6ce4-4649-a906-8f3c39c7de1b)

**Comment by ZoDDeL** [comment]
they didnt just renamed the files. this is a new compiled build.
they returned to an way older naming sheme they used before.
aside from that they dropped tripwire and beebyte/obfuscation.
but i dont know if the code for that is still there and inactive or if they totaly erased it.
also Ext.dll is gone without any replacement.
and we got unitycrashhandler64.exe

**Comment by InternetNinjo** [comment]
> they didnt just renamed the files. this is a new compiled build. they returned to an way older naming sheme they used before. aside from that they dropped tripwire and beebyte/obfuscation. but i dont know if the code for that is still there and inactive or if they totaly erased it. also Ext.dll is gone without any replacement. and we got unitycrashhandler64.exe

Yeah i got that from his post, the game did crash once 
when i was editing ammo values for both primary and secondary, it just completely crashed

**Comment by becauseimnoob** [comment]
@ZoDDeL I downloaded it despite all the risks, thinking that I would buy everything in the black market with great excitement, but the update came, and I guess this is my luck. When you bought everything in the market before I wanted to ask, did you need to open the script again? If you do, this is a local deception. Cosmetics only appear to you, I hope not.

**Comment by FireNinja7365** [comment]
> @ZoDDeL I downloaded it despite all the risks, thinking that I would buy everything in the black market with great excitement, but the update came, and I guess this is my luck. When you bought everything in the market before I wanted to ask, did you need to open the script again? If you do, this is a local deception. Cosmetics only appear to you, I hope not.

Skill issue

**Comment by ZoDDeL** [comment]
> @ZoDDeL I downloaded it despite all the risks, thinking that I would buy everything in the black market with great excitement, but the update came, and I guess this is my luck. When you bought everything in the market before I wanted to ask, did you need to open the script again? If you do, this is a local deception. Cosmetics only appear to you, I hope not.

what do you mean? black market script isnt working for your? then you table is outdated.
click on the top right button named "download latest table" to get the most current github commit.
after that you can click top right on "File - Save"

everything you buy with the free black market script got saved to your profile and is permanent.
same for the free bundles, operation rewards, daily task rewards, instant daily task (building a streak for the jäger skin).
also everything you equip with the multiSwapper stays equipped in your loadout even if you didnt unlock the stuff.

**Comment by InternetNinjo** [comment]
> > @ZoDDeL I downloaded it despite all the risks, thinking that I would buy everything in the black market with great excitement, but the update came, and I guess this is my luck. When you bought everything in the market before I wanted to ask, did you need to open the script again? If you do, this is a local deception. Cosmetics only appear to you, I hope not.
> 
> what do you mean? black market script isnt working for your? then you table is outdated. click on the top right button named "download latest table" to get the most current github commit. after that you can click top right on "File - Save"
> 
> everything you buy with the free black market script got saved to your profile and is permanent. same for the free bundles, operation rewards, daily task rewards, instant daily task (building a streak for the jäger skin). also everything you equip with the multiSwapper stays equipped in your loadout even if you didnt unlock the stuff.

for some reason, the operations are reset after they were making changes when the sensitive trigger is active till they rolled back. not sure if this is intentional

**Comment by ZoDDeL** [comment]
> for some reason, the operations are reset after they were making changes when the sensitive trigger is active till they rolled back. not sure if this is intentional

no idea what you talking about.
"sensitive trigger" ???
the opearation script is to unlock the opeartion rewards by just activating them so you can claim them without playing.

**Comment by InternetNinjo** [comment]
> > for some reason, the operations are reset after they were making changes when the sensitive trigger is active till they rolled back. not sure if this is intentional
> 
> no idea what you talking about. "sensitive trigger" ??? the opearation script is to unlock the opeartion rewards by just activating them so you can claim them without playing.

by the trigger = closes game when CT is present

and by operations i unlocked them all when the script got the unlocking feature for operational rewards, and suddenly i noticed i'm getting rewards manually by playing and then went to check, all of them were empty. i have no clue of what happened

**Comment by InternetNinjo** [comment]
> > by the trigger = closes game when CT is present
> > and by operations i unlocked them all when the script got the unlocking feature for operational rewards, and suddenly i noticed i'm getting rewards manually by playing and then went to check, all of them were empty. i have no clue of what happened
> 
> current game version 0.21.45 doesnt close when CE is open because they dropped the tripwire code. when you game closes its on your end and has nothing todo with CE.
> 
> again the operation script function is to unlock the rewards per mission. means you activate the script. start an operation, choose a mission, claim the rewards and repeat this by all mission until the whole mission tree is done. you get the rewards. you dont play the mission! and you didable the script if you dont use it. i hope you understand now. im tired of repeating this over and over. you can also watch it working here: https://www.youtube.com/watch?v=U5Q_2ws7ryk

didn't mean to confuse things more, more like my save file is corrupted, so it's not your fault
