### ISSUE TITLE
Vacuum Bot Not Working

### ISSUE THREAD

**Issue by honchoDev** [ZoDDeL/CM-Ultimate#2]
Not working not able to turn on because of line 29

**Comment by ZoDDeL** [comment]
thats wrong. everything works.
if not than its on your end.

use a proper installed cheatengine from cheatengine.org
make sure to run it as admin with all requirements.
use a 64bit windows 10 (i dont support trash 11)
use an cpu that isnt older than ryzen 3000 series.
