### ISSUE TITLE
Free bundle not working 

### ISSUE THREAD

**Issue by FLA-FLAN** [ZoDDeL/CM-Ultimate#4]
After the update the free bundle hack doesn't work, please fix it quickly

**Comment by FLA-FLAN** [comment]
If it can be fixed

**Comment by Sayan0100** [comment]
They(**Alfa Bravo** Dev) probably put the bundle into the server. The values/addresses are not fixed.

**Comment by MAX1MDEV** [comment]
> They(**Alfa Bravo** Dev) probably put the bundle into the server. The values/addresses are not fixed.

really?
