### ISSUE TITLE
Question for Loadout Modding

### ISSUE THREAD

**Issue by RustOsprey55681** [ZoDDeL/CM-Ultimate#9]
so i had to play on CM build 19.4 to use the Loadout modding script?

**Comment by ZoDDeL** [comment]
yes. just download the 19.4 game version (download links on my git main page) extract it somewhere and run game.exe.
your profile / savegame works on any game version.
so you can modify stuff like loadout on an older version and save it (options > account > save to cloud).
when done just close the game and rune the default current game version.

**Comment by RustOsprey55681** [comment]
I see. Thanks for the information, good sir.
